In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
import seaborn as snss
import missingno as msno
from scipy import stats
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import QuantileTransformer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import PolynomialFeatures
from scipy.stats import boxcox

In [2]:
df_train=pd.read_csv('train_final.csv')
df_test=pd.read_csv('test_final.csv')

In [3]:
print(df_train.shape)
target=df_train.Y
df_train.drop('Y',axis='columns',inplace=True)


(16383, 26)


In [4]:
frames=[df_train,df_test]
df=pd.concat(frames)


In [5]:
ID=df.Id
df1=df.drop('Id',axis='columns')
test_ID=ID[16383:]
test_ID.shape

(16385,)

In [6]:
scaler = MinMaxScaler((0,1))
#scaler = StandardScaler()
#scaler = PowerTransformer()
#scaler = QuantileTransformer()
#scaler = RobustScaler()
#scaler=MaxAbsScaler()
df2=np.array(df1)
scaler.fit(df2[:16383])
df3=scaler.transform(df2)
Norm_df=pd.DataFrame(df3)
#Norm_df=df1

In [7]:
Norm_df_train=Norm_df[:16383]
shuffle(Norm_df_train, random_state=1)

0    1        2         3    4    5         6         7    8   \
8129   0.140114  0.0  0.00000  0.359379  0.0  0.0  0.370395  0.368604  0.0   
11743  0.083264  0.0  0.00004  0.357870  0.0  0.0  0.370203  0.448511  0.0   
11536  0.090859  0.0  0.00000  0.359482  0.0  0.0  0.370395  0.401209  0.0   
10017  0.113720  0.0  0.00000  0.359379  0.0  0.0  0.370395  0.753801  0.0   
7369   0.080851  0.0  0.00000  0.359543  0.0  0.0  0.370395  0.376195  0.1   
...         ...  ...      ...       ...  ...  ...       ...       ...  ...   
16127  0.118419  0.0  0.00000  0.359216  0.0  0.0  0.371356  0.404985  0.0   
5192   0.074089  0.0  0.00000  0.359094  0.0  0.0  0.370395  0.408410  0.0   
12172  0.024597  0.0  0.00004  0.359094  0.0  0.0  0.370395  0.520202  0.0   
235    0.012343  0.0  0.00004  0.359706  0.0  0.0  0.370395  0.813964  0.0   
13349  0.106489  0.0  0.00004  0.358121  0.0  0.0  0.370395  0.380821  0.0   

             9   ...        14        15        16   17        18        19  \
8129   0.000000  ...  0.008243  0.410240  0.942199  0.0  0.000134  0.000000   
11743  0.000000  ...  0.170452  0.440458  0.377379  0.0  0.005072  0.285714   
11536  0.000000  ...  0.052039  0.409914  0.942199  0.0  0.014491  0.000000   
10017  0.000000  ...  0.009927  0.409892  0.378164  0.0  0.010155  0.000000   
7369   0.000199  ...  0.055302  0.404650  0.375706  0.0  0.000902  0.000000   
...         ...  ...       ...       ...       ...  ...       ...       ...   
16127  0.000794  ...  0.049257  0.403905  0.948341  0.0  0.005753  0.000000   
5192   0.000000  ...  0.024260  0.403126  0.377559  0.0  0.002949  0.000000   
12172  0.000199  ...  0.055725  0.408010  0.875309  0.0  0.001691  0.000000   
235    0.000596  ...  0.056364  0.415737  0.375706  0.0  0.002521  0.000000   
13349  0.000000  ...  0.346798  0.405135  0.377379  0.0  0.014269  0.000000   

        20   21            22   23  
8129   0.0  0.0  4.946961e-09  0.0  
11743  0.0  0.0  1.830376e-07  0.0  
11536  0.0  0.0  1.805641e-07  0.0  
10017  0.0  0.0  2.473480e-09  0.0  
7369   0.0  0.0  8.657181e-08  0.0  
...    ...  ...           ...  ...  
16127  0.0  0.0  0.000000e+00  0.0  
5192   0.0  0.0  0.000000e+00  0.0  
12172  0.0  0.0  4.452265e-08  0.0  
235    0.0  0.0  7.420441e-09  0.0  
13349  0.0  0.0  2.473480e-09  0.0  

[16383 rows x 24 columns]

In [8]:
Norm_df_test=Norm_df[16383:]


In [9]:
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import GradientBoostingClassifier

In [10]:
from sklearn.model_selection import cross_val_score
warnings.filterwarnings('ignore')
alphas = [400]
for i in alphas:
    model_xgb=  XGBClassifier(n_estimators=i,
                              base_score=0.1,
                              booster='gbtree',
                              colsample_bylevel=1,
                              colsample_bynode=1,
                              gamma=0,
                              learning_rate=0.3,
                              max_delta_step=0,
                              max_depth=6,
                              min_child_weight=1,
                              n_jobs=8,
                              reg_alpha=0,
                              reg_lambda=1,
                              scale_pos_weight=1,
                              random_state=0)
    n_scores = cross_val_score(model_xgb, Norm_df_train, target, scoring='roc_auc', cv=5).mean()
    print(n_scores)

[19:19:14] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[19:19:20] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[19:19:24] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[19:19:28] WARNING: C:/Users/Administrator/workspace/xgboost-win64_rel

In [17]:
sub_model=  XGBClassifier(n_estimators=400,
                              base_score=0.1,
                              booster='gbtree',
                              colsample_bylevel=1,
                              colsample_bynode=1,
                              gamma=0,
                              learning_rate=0.3,
                              max_delta_step=0,
                              max_depth=6,
                              min_child_weight=1,
                              n_jobs=8,
                              reg_alpha=0,
                              reg_lambda=1,
                              scale_pos_weight=1,
                              random_state=0)
sub_model.fit(Norm_df_train,target)

[19:20:32] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.1, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.3, max_delta_step=0,
              max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=800, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [18]:
h=sub_model.predict_proba(Norm_df_test)
y_newpred=h[:,1]
y_newpred

array([0.9939838 , 0.9980069 , 1.        , ..., 0.9999995 , 0.99771464,
       0.9983796 ], dtype=float32)

In [20]:
from sklearn.model_selection import cross_val_score
alphas = [500] 
for i in alphas:
    model_randomforest= RandomForestClassifier(n_estimators=i,
                                               max_features='auto',
                                               min_samples_leaf=2,
                                               min_samples_split=2,
                                               max_depth=50,
                                               min_weight_fraction_leaf=0,
                                               max_leaf_nodes=1000,
                                               criterion='entropy',
                                               min_impurity_decrease=0,
                                               n_jobs=1,
                                               class_weight='balanced_subsample',
                                               ccp_alpha=0,
                                               random_state=0)
    n_scores = cross_val_score(model_randomforest, Norm_df_train, target, scoring='roc_auc', cv=5).mean()
    print(n_scores)

0.8832868677831426


In [49]:
sub_rfmodel=RandomForestClassifier(n_estimators=500,
                                               max_features='auto',
                                               min_samples_leaf=2,
                                               min_samples_split=2,
                                               max_depth=50,
                                               min_weight_fraction_leaf=0,
                                               max_leaf_nodes=1000,
                                               criterion='entropy',
                                               min_impurity_decrease=0,
                                               n_jobs=1,
                                               class_weight='balanced_subsample',
                                               ccp_alpha=0,
                                               random_state=0)
sub_rfmodel.fit(Norm_df_train,target)

RandomForestClassifier(ccp_alpha=0, class_weight='balanced_subsample',
                       criterion='entropy', max_depth=50, max_leaf_nodes=1000,
                       min_impurity_decrease=0, min_samples_leaf=2,
                       min_weight_fraction_leaf=0, n_estimators=500, n_jobs=1,
                       random_state=0)

In [50]:
h1=sub_rfmodel.predict_proba(Norm_df_test)
y_newpred1=h1[:,1]
y_newpred1

array([0.82328834, 0.6861963 , 0.98372147, ..., 0.99811793, 0.91052192,
       0.87437623])

In [54]:
from sklearn.model_selection import cross_val_score
alphas = [300,400,500,600,700] 
for i in alphas:
    model_GBM= GradientBoostingClassifier(n_estimators=i,
                                              random_state=0)
    n_scores = cross_val_score(model_GBM, Norm_df_train, target, scoring='roc_auc', cv=5).mean()
    print(n_scores)

0.8610617931648399
0.8652238467889841
0.8667171816811223
0.8702866694144207
0.871583466819516


In [55]:
model_GBM= GradientBoostingClassifier(n_estimators=i,
                                              random_state=0)
model_GBM.fit(Norm_df_train,target)

GradientBoostingClassifier(n_estimators=700, random_state=0)

In [56]:
h2=model_GBM.predict_proba(Norm_df_test)
y_newpred2=h2[:,1]
y_newpred2

array([0.82146828, 0.89264176, 0.99951746, ..., 0.99886593, 0.9790729 ,
       0.96157339])

In [66]:
real_pred=0.3*y_newpred+0.4*y_newpred1+0.3*y_newpred2

In [67]:
real_pred

array([0.87395097, 0.84167314, 0.99334384, ..., 0.99890681, 0.95724505,
       0.93773639])

In [68]:
output2 = pd.DataFrame({'id':test_ID,'Y':real_pred})
output2.to_csv('rf+xgb1111.csv', index=False)