In [ ]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
from mlxtend.classifier import StackingClassifier
import seaborn as snss
import missingno as msno
from scipy import stats
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn import metrics
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import QuantileTransformer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import AdaBoostClassifier
from scipy.stats import boxcox
import xgboost as xgb
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [4]:
df_train=pd.read_csv('train_final.csv')
df_test=pd.read_csv('test_final.csv')

In [5]:
print(df_train.shape)
target=df_train.Y
df_train.drop('Y',axis='columns',inplace=True)


(16383, 26)


In [6]:
frames=[df_train,df_test]
df=pd.concat(frames)


In [7]:
ID=df.Id
df1=df.drop('Id',axis='columns')
test_ID=ID[16383:]
test_ID.shape

(16385,)

In [8]:
df1

f1  f2     f3      f4  f5  f6      f7      f8  f9  f10  ...    f15  \
0       25884   1  33.63  118596   1   0  118595  125738   1    3  ...   1945   
1       34346   1  10.62  118041   1   0  117902  130913   1    1  ...  15385   
2       34923   1   1.77  118327   1   0  117961  124402   1    2  ...   7547   
3       80926   1  30.09  118300   1   0  117961  301218   1    0  ...   4933   
4        4674   1   1.77  119921   1   0  119920  302830   1    0  ...  13836   
...       ...  ..    ...     ...  ..  ..     ...     ...  ..  ...  ...    ...   
16380     971   1   1.77  118300   1   0  117961  310997   1    0  ...   4864   
16381  105802   1   1.77  118327   1   0  117961  117906   1    0  ...  32457   
16382   43096   1   3.54  117962   1   0  117961  118368   1    0  ...   2014   
16383   31220   1   1.77  118386   1   0  117961  117906   1    1  ...   1249   
16384   41642   1   3.54  118052   1   0  117961  172635   1    4  ...  13854   

          f16     f17  f18     f19  f20  f21  f22  f23  f24  
0      118450  119184    1  121372    1    1    1    2    1  
1      117945  292795    1  259173    1    1    1    1    1  
2      118933  290919    1  118784    1    1    1    1    1  
3      118458  118331    1  307024    1    1    1    2    1  
4      142145    4673    1  128230    1    1    1  620    1  
...       ...     ...  ...     ...  ...  ...  ...  ...  ...  
16380  123055  118424    1  120344    1    1    1   44    1  
16381  118320  290919    1  118321    1    1    1    4    1  
16382  117904  117887    1  118368    1    1    1    1    1  
16383  118910  290919    1  118321    1    1    1    2    2  
16384  118821  290919    1  117905    1    1    1    1    1  

[32768 rows x 24 columns]

In [9]:
#scaler = MinMaxScaler((0,1))
#df2=np.array(df1)
##scaler.fit(df2)
#df3=scaler.transform(df2)
#Norm_df=pd.DataFrame(df3)
Norm_df=df1

In [10]:
Norm_df_train=Norm_df[:16383]
shuffle(Norm_df_train, random_state=1)

f1  f2    f3      f4  f5  f6      f7      f8  f9  f10  ...     f15  \
8129   43736   1  1.77  118300   1   0  117961  117906   1    0  ...    2594   
11743  25990   1  3.54  117903   1   0  117902  142453   1    0  ...   53150   
11536  28361   1  1.77  118327   1   0  117961  127922   1    0  ...   16244   
10017  35497   1  1.77  118300   1   0  117961  236236   1    0  ...    3119   
7369   25237   1  1.77  118343   1   0  117961  120238   2    1  ...   17261   
...      ...  ..   ...     ...  ..  ..     ...     ...  ..  ...  ...     ...   
16127  36964   1  1.77  118257   1   0  118256  129082   1    4  ...   15377   
5192   23126   1  1.77  118225   1   0  117961  130134   1    0  ...    7586   
12172   7677   1  3.54  118225   1   0  117961  164476   1    1  ...   17393   
235     3852   1  3.54  118386   1   0  117961  254718   1    3  ...   17592   
13349  33240   1  3.54  117969   1   0  117961  121659   1    0  ...  108112   

          f16     f17  f18     f19  f20  f21  f22  f23  f24  
8129   120410  290919    1  117905    1    1    1    3    1  
11743  128935  118398    1  118863    3    1    1   75    1  
11536  120318  290919    1  120690    1    1    1   74    1  
10017  120312  118638    1  119849    1    1    1    2    1  
7369   118833  117887    1  118054    1    1    1   36    1  
...       ...     ...  ...     ...  ...  ...  ...  ...  ...  
16127  118623  292795    1  118995    1    1    1    1    1  
5192   118403  118453    1  118451    1    1    1    1    1  
12172  119781  270488    1  118207    1    1    1   19    1  
235    121961  117887    1  118368    1    1    1    4    1  
13349  118970  118398    1  120647    1    1    1    2    1  

[16383 rows x 24 columns]

In [11]:
Norm_df_test=Norm_df[16383:]
Norm_df_test

f1  f2     f3      f4  f5  f6      f7      f8  f9  f10  ...    f15  \
0       37733   1   1.77  118603   1   0  118602  118097   1    0  ...  13881   
1      312129   1   3.54  118052   1   0  117961  290919   1    4  ...  14638   
2       24884   1  23.01  118300   1   0  117961  302830   1    0  ...    770   
3        4674   1   1.77  119091   1   0  119062  118036   1    9  ...  16752   
4       68725   1   3.54  118300   1   0  117961  171056   1    0  ...   4945   
...       ...  ..    ...     ...  ..  ..     ...     ...  ..  ...  ...    ...   
16380     971   1   1.77  118300   1   0  117961  310997   1    0  ...   4864   
16381  105802   1   1.77  118327   1   0  117961  117906   1    0  ...  32457   
16382   43096   1   3.54  117962   1   0  117961  118368   1    0  ...   2014   
16383   31220   1   1.77  118386   1   0  117961  117906   1    1  ...   1249   
16384   41642   1   3.54  118052   1   0  117961  172635   1    4  ...  13854   

          f16     f17  f18     f19  f20  f21  f22  f23  f24  
0      117941  117887    1  117885    1    1    1    1    1  
1      118992  290919    1  118321    1    1    1    7    1  
2      119181    4673    1  128230    1    1    1   14    1  
3      143531  290919    1  117905    1    1    1   81    1  
4      118360  118638    1  118636    1    1    1    1    1  
...       ...     ...  ...     ...  ...  ...  ...  ...  ...  
16380  123055  118424    1  120344    1    1    1   44    1  
16381  118320  290919    1  118321    1    1    1    4    1  
16382  117904  117887    1  118368    1    1    1    1    1  
16383  118910  290919    1  118321    1    1    1    2    2  
16384  118821  290919    1  117905    1    1    1    1    1  

[16385 rows x 24 columns]

In [12]:
from sklearn.model_selection import cross_val_score
alphas = [500] 
for i in alphas:
    model_randomforest= RandomForestClassifier(n_estimators=i,
                                               max_features='auto',
                                               min_samples_leaf=2,
                                               min_samples_split=2,
                                               max_depth=50,
                                               min_weight_fraction_leaf=0,
                                               max_leaf_nodes=1000,
                                               criterion='entropy',
                                               min_impurity_decrease=0,
                                               n_jobs=1,
                                               class_weight='balanced_subsample',
                                               ccp_alpha=0,
                                               random_state=0)
    n_scores = cross_val_score(model_randomforest, Norm_df_train, target, scoring='roc_auc', cv=5).mean()
    print(n_scores)

0.8770118165153372


In [13]:
sub_model=RandomForestClassifier(n_estimators=500,
                                               max_features='auto',
                                               min_samples_leaf=2,
                                               min_samples_split=2,
                                               max_depth=50,
                                               min_weight_fraction_leaf=0,
                                               max_leaf_nodes=1000,
                                               criterion='entropy',
                                               min_impurity_decrease=0,
                                               n_jobs=1,
                                               class_weight='balanced_subsample',
                                               ccp_alpha=0,
                                               random_state=0)
sub_model.fit(Norm_df_train,target)

RandomForestClassifier(ccp_alpha=0, class_weight='balanced_subsample',
                       criterion='entropy', max_depth=50, max_leaf_nodes=1000,
                       min_impurity_decrease=0, min_samples_leaf=2,
                       min_weight_fraction_leaf=0, n_estimators=500, n_jobs=1,
                       random_state=0)

In [14]:
h=sub_model.predict_proba(Norm_df_test)
y_newpred=h[:,1]
y_newpred

array([0.78359342, 0.71960852, 0.97989426, ..., 0.99249053, 0.91852119,
       0.89845106])

In [16]:
sub_model1=RandomForestClassifier(n_estimators=600,
                                               max_features='auto',
                                               min_samples_leaf=2,
                                               min_samples_split=2,
                                               max_depth=50,
                                               min_weight_fraction_leaf=0,
                                               max_leaf_nodes=1000,
                                               criterion='entropy',
                                               min_impurity_decrease=0,
                                               n_jobs=1,
                                               class_weight='balanced_subsample',
                                               ccp_alpha=0,
                                               random_state=0)
sub_model1.fit(Norm_df_train,target)

RandomForestClassifier(ccp_alpha=0, class_weight='balanced_subsample',
                       criterion='entropy', max_depth=50, max_leaf_nodes=1000,
                       min_impurity_decrease=0, min_samples_leaf=2,
                       min_weight_fraction_leaf=0, n_estimators=600, n_jobs=1,
                       random_state=0)

In [17]:
h1=sub_model1.predict_proba(Norm_df_test)
y_newpred1=h1[:,1]
y_newpred1

array([0.78451943, 0.69848947, 0.9812247 , ..., 0.99207544, 0.91411981,
       0.88985049])

In [24]:
real_pred=0.55*y_newpred+0.45*y_newpred1
real_pred

array([0.78401013, 0.71010495, 0.98049296, ..., 0.99230374, 0.91654057,
       0.8945808 ])

In [25]:
output2 = pd.DataFrame({'id':test_ID,'Y':y_newpred})
output2.to_csv('rf1+rf2.csv', index=False)